>>> type([12,13,145,15])
<class 'list'>
>>> type((12,13,14,15))
<class 'tuple'>
>>> type(["merhaba",12])
<class 'list'>
>>> type({"merhaba","Mustafa"})
<class 'set'>
>>> type({"merhaba":"Musa"})
<class 'dict'>
